import { Hono } from 'hono'
import { zValidator } from '@hono/zod-validator'
import {
  TranscriptQuerySchema,
  type TranscriptResponse,
  type TranscriptSegment,
} from '@ytmod/shared'

type Bindings = { YOUTUBE_API_KEY: string }

export const transcript = new Hono<{ Bindings: Bindings }>()

// Rate limit: 20 req/min per IP
const rateMap = new Map<string, { count: number; reset: number }>()

transcript.use('*', async (c, next) => {
  const ip = c.req.header('CF-Connecting-IP') ?? c.req.header('X-Forwarded-For') ?? 'unknown'
  const now = Date.now()
  const entry = rateMap.get(ip)
  if (!entry || now > entry.reset) {
    rateMap.set(ip, { count: 1, reset: now + 60_000 })
  } else if (entry.count >= 20) {
    return c.json({ error: 'Rate limit exceeded. Try again in a minute.' }, 429)
  } else {
    entry.count++
  }
  return next()
})

transcript.get('/', zValidator('query', TranscriptQuerySchema), async (c) => {
  const { videoId, lang } = c.req.valid('query')
  const apiKey = c.env.YOUTUBE_API_KEY

  // Fetch video title — non-fatal
  let videoTitle: string | undefined
  try {
    const vRes = await fetch(
      `https://www.googleapis.com/youtube/v3/videos?part=snippet&id=${videoId}&key=${apiKey}`
    )
    if (vRes.ok) {
      const vData = (await vRes.json()) as { items: Array<{ snippet: { title: string } }> }
      videoTitle = vData.items[0]?.snippet?.title
    }
  } catch {
    /* swallow */
  }

  // Try requested lang, then 'en' fallback, then auto-generated
  const attempts = [
    { lang, auto: false },
    { lang: 'en', auto: false },
    { lang, auto: true },
    { lang: 'en', auto: true },
  ]

  for (const attempt of attempts) {
    const url = `https://www.youtube.com/api/timedtext?v=${videoId}&lang=${attempt.lang}&fmt=json3${attempt.auto ? '&kind=asr' : ''}`
    const res = await fetch(url)

    if (!res.ok) continue

    const text = await res.text()
    if (!text || text === '{}' || text.length < 10) continue

    let data: {
      events?: Array<{ tStartMs: number; dDurationMs: number; segs?: Array<{ utf8: string }> }>
    }
    try {
      data = JSON.parse(text)
    } catch {
      continue
    }

    if (!data.events?.length) continue

    const segments: TranscriptSegment[] = data.events
      .filter((e) => e.segs)
      .map((e) => ({
        text: e
          .segs!.map((s) => s.utf8)
          .join('')
          .trim(),
        start: e.tStartMs / 1000,
        duration: e.dDurationMs / 1000,
      }))
      .filter((s) => s.text)

    if (!segments.length) continue

    const response: TranscriptResponse = {
      videoId,
      videoTitle,
      language: attempt.lang,
      autoGenerated: attempt.auto,
      segments,
    }

    return c.json(response)
  }

  return c.json({ error: 'Transcript not available for this video.' }, 404)
})
