import { describe, it, expect, vi, beforeEach } from 'vitest'
import app from '../index'

const mockTimedtext = JSON.stringify({
  events: [
    { tStartMs: 0, dDurationMs: 2000, segs: [{ utf8: 'Hello ' }, { utf8: 'world' }] },
    { tStartMs: 2000, dDurationMs: 3000, segs: [{ utf8: 'This is a test' }] },
    { tStartMs: 5000, dDurationMs: 1000 }, // no segs — should be filtered
  ],
})

const mockEnv = {
  YOUTUBE_API_KEY: 'test-key',
  CORS_ORIGINS: 'http://localhost:5173',
  CLIPPER_ENGINE_URL: 'http://localhost:8080',
}

beforeEach(() => {
  vi.restoreAllMocks()
})

describe('GET /transcript', () => {
  it('returns 400 on missing videoId', async () => {
    const res = await app.request('/transcript', {}, mockEnv)
    expect(res.status).toBe(400)
  })

  it('returns transcript segments', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn().mockImplementation((url: string) => {
        if (url.includes('googleapis'))
          return Promise.resolve({
            ok: true,
            json: () => Promise.resolve({ items: [{ snippet: { title: 'Test Video' } }] }),
          })
        if (url.includes('timedtext'))
          return Promise.resolve({ ok: true, text: () => Promise.resolve(mockTimedtext) })
        return Promise.resolve({ ok: false })
      })
    )

    const res = await app.request('/transcript?videoId=dQw4w9WgXcQ', {}, mockEnv)
    expect(res.status).toBe(200)
    const data = (await res.json()) as {
      segments: Array<{ text: string; start: number }>
      videoTitle: string
      autoGenerated: boolean
    }
    expect(data.segments).toHaveLength(2)
    expect(data.segments[0].text).toBe('Hello world')
    expect(data.segments[0].start).toBe(0)
    expect(data.videoTitle).toBe('Test Video')
    expect(data.autoGenerated).toBe(false)
  })

  it('returns 404 when transcript unavailable', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue({ ok: false, text: () => Promise.resolve('') })
    )
    const res = await app.request('/transcript?videoId=dQw4w9WgXcQ', {}, mockEnv)
    expect(res.status).toBe(404)
  })
})
