import { Hono } from 'hono'
import { zValidator } from '@hono/zod-validator'
import {
  TranscriptQuerySchema,
  type TranscriptResponse,
  type TranscriptSegment,
} from '@ytmod/shared'

type Bindings = { YOUTUBE_API_KEY: string }

export const transcript = new Hono<{ Bindings: Bindings }>()

// Rate limit: 20 req/min per IP
const rateMap = new Map<string, { count: number; reset: number }>()

transcript.use('*', async (c, next) => {
  const ip = c.req.header('CF-Connecting-IP') ?? c.req.header('X-Forwarded-For') ?? 'unknown'
  const now = Date.now()
  const entry = rateMap.get(ip)
  if (!entry || now > entry.reset) {
    rateMap.set(ip, { count: 1, reset: now + 60_000 })
  } else if (entry.count >= 20) {
    return c.json({ error: 'Rate limit exceeded. Try again in a minute.' }, 429)
  } else {
    entry.count++
  }
  return next()
})

// Task 2.1 — ekstrak 11-char video ID dari berbagai format input
export function extractVideoId(input: string): string | null {
  const trimmed = input.trim()
  if (!trimmed) return null

  // Coba parse sebagai URL
  try {
    const url = new URL(trimmed)
    const host = url.hostname.replace(/^www\./, '')

    if (host === 'youtube.com' || host === 'm.youtube.com') {
      const v = url.searchParams.get('v')
      if (v) return validateVideoId(v) ? v : null

      const embedMatch = url.pathname.match(/^\/embed\/([a-zA-Z0-9_-]{11})/)
      if (embedMatch) return embedMatch[1]
    }

    if (host === 'youtu.be') {
      const id = url.pathname.slice(1).split('?')[0]
      return validateVideoId(id) ? id : null
    }
  } catch {
    // Bukan URL — coba sebagai ID langsung
  }

  // ID langsung 11 karakter
  return validateVideoId(trimmed) ? trimmed : null
}

// Task 2.2 — validasi pattern [a-zA-Z0-9_-]{11}
export function validateVideoId(id: string): boolean {
  return /^[a-zA-Z0-9_-]{11}$/.test(id)
}

// Task 2.3 — fungsi murni untuk parsing timedtext events
export type TimedtextEvent = {
  tStartMs: number
  dDurationMs: number
  segs?: Array<{ utf8: string }>
}

export function parseTimedtext(events: TimedtextEvent[]): TranscriptSegment[] {
  return events
    .filter((e) => e.segs)
    .map((e) => {
      const raw = e.segs!.map((s) => s.utf8).join('')
      const text = stripHtml(raw).trim()
      return {
        text,
        start: e.tStartMs / 1000,
        duration: e.dDurationMs / 1000,
      }
    })
    .filter((s) => s.text)
}

function stripHtml(input: string): string {
  return input
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/<[^>]+>/g, '')
}

transcript.get('/', zValidator('query', TranscriptQuerySchema), async (c) => {
  const { videoId: rawVideoId, lang } = c.req.valid('query')
  const apiKey = c.env.YOUTUBE_API_KEY

  // Task 2.1 — ekstrak video ID dari URL atau ID langsung
  const videoId = extractVideoId(rawVideoId)

  // Task 2.2 — validasi setelah ekstraksi
  if (!videoId) {
    return c.json({ error: 'Invalid videoId format' }, 400)
  }

  // Fetch video title — non-fatal
  let videoTitle: string | undefined
  try {
    const vRes = await fetch(
      `https://www.googleapis.com/youtube/v3/videos?part=snippet&id=${videoId}&key=${apiKey}`
    )
    if (vRes.ok) {
      const vData = (await vRes.json()) as { items: Array<{ snippet: { title: string } }> }
      videoTitle = vData.items[0]?.snippet?.title
    }
  } catch {
    /* swallow */
  }

  // Try requested lang, then 'en' fallback, then auto-generated
  const attempts = [
    { lang, auto: false },
    { lang: 'en', auto: false },
    { lang, auto: true },
    { lang: 'en', auto: true },
  ]

  for (const attempt of attempts) {
    const url = `https://www.youtube.com/api/timedtext?v=${videoId}&lang=${attempt.lang}&fmt=json3${attempt.auto ? '&kind=asr' : ''}`
    const res = await fetch(url)

    if (!res.ok) continue

    const text = await res.text()
    if (!text || text === '{}' || text.length < 10) continue

    let data: { events?: TimedtextEvent[] }
    try {
      data = JSON.parse(text)
    } catch {
      continue
    }

    if (!data.events?.length) continue

    // Task 2.3 — gunakan parseTimedtext()
    const segments = parseTimedtext(data.events)

    if (!segments.length) continue

    const response: TranscriptResponse = {
      videoId,
      videoTitle,
      language: attempt.lang,
      autoGenerated: attempt.auto,
      segments,
    }

    return c.json(response)
  }

  return c.json({ error: 'Transcript not available for this video.' }, 404)
})
