import { describe, it, expect } from 'vitest'
import * as fc from 'fast-check'
import {
  CommentsQuerySchema,
  CommentsResponseSchema,
  CommentSchema,
  TranscriptQuerySchema,
  TranscriptResponseSchema,
  TranscriptSegmentSchema,
} from './index'

describe('CommentsQuerySchema', () => {
  it('parses valid query', () => {
    const result = CommentsQuerySchema.parse({ videoId: 'abc123' })
    expect(result.maxResults).toBe(20)
    expect(result.order).toBe('relevance')
  })

  it('rejects empty videoId', () => {
    expect(() => CommentsQuerySchema.parse({ videoId: '' })).toThrow()
  })

  it('coerces maxResults from string', () => {
    const result = CommentsQuerySchema.parse({ videoId: 'abc', maxResults: '50' })
    expect(result.maxResults).toBe(50)
  })

  it('clamps maxResults to 100', () => {
    expect(() => CommentsQuerySchema.parse({ videoId: 'abc', maxResults: 101 })).toThrow()
  })

  it('rejects invalid order', () => {
    expect(() => CommentsQuerySchema.parse({ videoId: 'abc', order: 'invalid' })).toThrow()
  })
})

describe('CommentSchema', () => {
  it('parses valid comment', () => {
    const comment = CommentSchema.parse({
      id: '1',
      author: 'user',
      text: 'hello',
      likeCount: 5,
      publishedAt: '2024-01-01T00:00:00Z',
    })
    expect(comment.replyCount).toBeUndefined()
  })
})

describe('CommentsResponseSchema', () => {
  it('parses valid response', () => {
    const res = CommentsResponseSchema.parse({
      videoId: 'abc',
      totalComments: 100,
      comments: [],
    })
    expect(res.nextPageToken).toBeUndefined()
    expect(res.videoTitle).toBeUndefined()
  })
})

describe('TranscriptQuerySchema', () => {
  it('defaults lang to id', () => {
    expect(TranscriptQuerySchema.parse({ videoId: 'abc' }).lang).toBe('id')
  })

  it('rejects empty videoId', () => {
    expect(() => TranscriptQuerySchema.parse({ videoId: '' })).toThrow()
  })
})

describe('TranscriptSegmentSchema', () => {
  it('parses valid segment', () => {
    const seg = TranscriptSegmentSchema.parse({ text: 'hello', start: 1.5, duration: 2.0 })
    expect(seg.text).toBe('hello')
  })
})

describe('TranscriptResponseSchema', () => {
  it('parses valid response', () => {
    const res = TranscriptResponseSchema.parse({
      videoId: 'abc',
      language: 'id',
      autoGenerated: false,
      segments: [],
    })
    expect(res.videoTitle).toBeUndefined()
  })
})

// Feature: transcriber, Property 5: TranscriptResponse JSON round-trip
describe('Property 5: TranscriptResponse JSON round-trip', () => {
  /**
   * Arbitrary untuk TranscriptSegment — generate nilai number finite
   * agar JSON.stringify/parse tidak menghasilkan null (NaN/Infinity tidak valid JSON).
   */
  const segmentArb = fc.record({
    text: fc.string(),
    start: fc.float({ noNaN: true, noDefaultInfinity: true, min: 0 }),
    duration: fc.float({ noNaN: true, noDefaultInfinity: true, min: 0 }),
  })

  /**
   * Arbitrary untuk TranscriptResponse lengkap, termasuk videoTitle opsional.
   * Validates: Requirements 2.5, 6.4
   */
  const transcriptResponseArb = fc.record({
    videoId: fc.string({ minLength: 1 }),
    videoTitle: fc.option(fc.string(), { nil: undefined }),
    language: fc.string({ minLength: 1 }),
    autoGenerated: fc.boolean(),
    segments: fc.array(segmentArb),
  })

  it('serialize ke JSON lalu parse kembali menghasilkan data yang equivalent', () => {
    fc.assert(
      fc.property(transcriptResponseArb, (original) => {
        // Serialize ke JSON string lalu parse kembali
        const json = JSON.stringify(original)
        const parsed = JSON.parse(json)

        // Validasi dengan schema — memastikan shape tetap valid setelah round-trip
        const result = TranscriptResponseSchema.parse(parsed)

        // Setiap field harus identik
        expect(result.videoId).toBe(original.videoId)
        expect(result.language).toBe(original.language)
        expect(result.autoGenerated).toBe(original.autoGenerated)
        expect(result.videoTitle).toBe(original.videoTitle)
        expect(result.segments).toHaveLength(original.segments.length)

        // Setiap segment harus identik field per field
        result.segments.forEach((seg, i) => {
          expect(seg.text).toBe(original.segments[i].text)
          expect(seg.start).toBe(original.segments[i].start)
          expect(seg.duration).toBe(original.segments[i].duration)
        })
      }),
      { numRuns: 100 }
    )
  })
})
