<script lang="ts">
  import type { TranscriptResponse } from '@ytmod/shared'
  import { extractVideoId, formatTxt, formatSrt } from '$lib/transcript'
  import { authFetch, requireAuth, getToken } from '$lib/auth'
  import { goto } from '$app/navigation'
  import { base } from '$app/paths'
  import { onMount } from 'svelte'

  const API_BASE = import.meta.env.VITE_API_URL
  if (!API_BASE) throw new Error('VITE_API_URL is not set')

  // Redirect ke /login jika belum auth saat halaman dibuka
  onMount(() => {
    if (!getToken()) goto(`${base}/login`)
  })

  let videoInput = $state('')
  let lang = $state('id')
  let loading = $state(false)
  let error = $state('')
  let result = $state<TranscriptResponse | null>(null)

  async function fetchTranscript() {
    if (!videoInput.trim()) return
    requireAuth()
    loading = true
    error = ''
    result = null

    const videoId = extractVideoId(videoInput) ?? videoInput.trim()
    try {
      const res = await authFetch(`${API_BASE}/transcript?videoId=${videoId}&lang=${lang}`)
      if (!res.ok) {
        const data = (await res.json()) as { error: string }
        throw new Error(data.error ?? `HTTP ${res.status}`)
      }
      result = (await res.json()) as TranscriptResponse
    } catch (e) {
      error = e instanceof Error ? e.message : 'Terjadi kesalahan'
    } finally {
      loading = false
    }
  }

  function download(content: string, filename: string, type: string) {
    const a = document.createElement('a')
    a.href = URL.createObjectURL(new Blob([content], { type }))
    a.download = filename
    a.click()
  }

  function downloadTxt() {
    if (!result) return
    download(formatTxt(result.segments), `transcript-${result.videoId}.txt`, 'text/plain')
  }

  function downloadSrt() {
    if (!result) return
    download(formatSrt(result.segments), `transcript-${result.videoId}.srt`, 'text/plain')
  }
</script>

<svelte:head>
  <title>YTMod — Transcript Downloader</title>
</svelte:head>

<main>
  <h1>YouTube Transcript</h1>
  <p class="subtitle">Unduh subtitle/transcript video YouTube</p>

  <form
    onsubmit={(e) => {
      e.preventDefault()
      fetchTranscript()
    }}
  >
    <div class="input-row">
      <input
        type="text"
        bind:value={videoInput}
        placeholder="URL atau Video ID YouTube"
        aria-label="URL atau Video ID YouTube"
        disabled={loading}
      />
      <button type="submit" disabled={loading || !videoInput.trim()}>
        {loading ? 'Mengambil...' : 'Ambil Transcript'}
      </button>
    </div>
    <div class="filter-row">
      <label>
        Bahasa
        <select bind:value={lang} disabled={loading}>
          <option value="id">Indonesia</option>
          <option value="en">English</option>
        </select>
      </label>
    </div>
  </form>

  {#if error}
    <p class="error" role="alert">{error}</p>
  {/if}

  {#if result}
    <div class="result">
      {#if result.videoTitle}
        <h2 class="video-title">"{result.videoTitle}"</h2>
      {/if}

      <div class="result-header">
        <span>
          {result.segments.length} segmen · bahasa: <strong>{result.language}</strong>
          {#if result.autoGenerated}<span class="badge">auto-generated</span>{/if}
        </span>
        <div class="actions">
          <button onclick={downloadTxt}>Unduh TXT</button>
          <button onclick={downloadSrt}>Unduh SRT</button>
        </div>
      </div>

      <div class="transcript">
        {#each result.segments as seg (seg.start)}
          <p>
            <span class="timestamp">{new Date(seg.start * 1000).toISOString().slice(11, 19)}</span>
            {seg.text}
          </p>
        {/each}
      </div>
    </div>
  {/if}
</main>

<style>
  main {
    max-width: 720px;
    margin: 0 auto;
    padding: 2rem 1rem;
    font-family: system-ui, sans-serif;
  }

  h1 {
    margin-bottom: 0.25rem;
  }
  .subtitle {
    color: #666;
    margin-bottom: 2rem;
  }

  .input-row {
    display: flex;
    gap: 0.5rem;
    margin-bottom: 0.75rem;
  }
  .filter-row {
    display: flex;
    gap: 1.5rem;
    margin-bottom: 1rem;
    font-size: 0.875rem;
    color: #555;
  }
  .filter-row label {
    display: flex;
    align-items: center;
    gap: 0.4rem;
  }

  select {
    padding: 0.3rem 0.5rem;
    border: 1px solid #ccc;
    border-radius: 4px;
    font-size: 0.875rem;
  }

  input {
    flex: 1;
    padding: 0.6rem 0.8rem;
    border: 1px solid #ccc;
    border-radius: 6px;
    font-size: 1rem;
  }

  button {
    padding: 0.6rem 1.2rem;
    background: #e00;
    color: white;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-size: 1rem;
  }

  button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  .error {
    color: #c00;
  }

  .video-title {
    font-size: 1.1rem;
    font-weight: 600;
    margin-bottom: 0.75rem;
  }

  .result-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1rem;
    font-size: 0.875rem;
    color: #555;
  }

  .badge {
    background: #f0f0f0;
    border: 1px solid #ddd;
    border-radius: 4px;
    padding: 0.1rem 0.4rem;
    font-size: 0.75rem;
    margin-left: 0.25rem;
  }

  .actions {
    display: flex;
    gap: 0.5rem;
  }
  .actions button {
    background: #333;
    font-size: 0.875rem;
  }

  .transcript {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    max-height: 60vh;
    overflow-y: auto;
    border: 1px solid #eee;
    border-radius: 8px;
    padding: 1rem;
  }

  .transcript p {
    margin: 0;
    line-height: 1.6;
  }

  .timestamp {
    font-size: 0.75rem;
    color: #999;
    font-family: monospace;
    margin-right: 0.5rem;
  }
</style>
